### PR TITLE
Add DPG Badge

### PR DESCRIPTION
**Pull request by BolajiAyodeji**
This PR includes the new DPG badge to the README file following [the guide](https://github.com/DPGAlliance/dpg-resources/blob/main/docs/dpg-badge-usage.md) and links to GlobalLeaks new profile page URL on the [DPG Registry](https://www.digitalpublicgoods.net/registry).

- [x] The pull request includes a description of the problem you're trying to solve.
- [x] The pull request provides an overview of the suggested solution.
- [x] The proposed code is fully functional.
- [ ] The proposed code includes relevant tests to verify its functionality.
- [ ] All new and existing tests pass successfully.
- [ ] Overall code quality and test coverage metrics are not reduced by more than 0.5%

### CODE REVIEW

**Comment by evilaliv3** [comment]
Thank you so much @BolajiAyodeji !

Going to merge this right away!

**Comment by BolajiAyodeji** [comment]
Hi @evilaliv3! Would it be possible to revert the color of the DPG badge in use to `3333AB` instead of `green` and make the DPG in caps, to ensure uniformity and brand familiarity with other DPGs ([ref](https://github.com/DPGAlliance/dpg-resources/blob/main/docs/dpg-badge-usage.md))? I understand you may prefer green since it goes with the other badges in use. I can submit a PR to make the changes, but thought to notify you first. Thanks!

---

Current:
<a href="https://github.com/globaleaks/globaleaks-whistleblowing-software/blob/stable/CODE_OF_CONDUCT.md">Code of Conduct</a> <a href="https://www.bestpractices.dev/projects/3816"></a> <a href="https://scorecard.dev/viewer/?uri=github.com/globaleaks/globaleaks-whistleblowing-software"></a> <a href="https://digitalpublicgoods.net/r/globaleaks">DPG Badge</a>

Proposal:
<a href="https://github.com/globaleaks/globaleaks-whistleblowing-software/blob/stable/CODE_OF_CONDUCT.md">Code of Conduct</a> <a href="https://www.bestpractices.dev/projects/3816"></a> <a href="https://scorecard.dev/viewer/?uri=github.com/globaleaks/globaleaks-whistleblowing-software"></a> <a href="https://digitalpublicgoods.net/r/globaleaks">DPG Badge</a>

**Comment by evilaliv3** [comment]
Absolutely yes @BolajiAyodeji ! 

I just restored the correct brand color of DPG. Thank you!

**Comment by BolajiAyodeji** [comment]
> Absolutely yes @BolajiAyodeji !
> 
> I just restored the correct brand color of DPG. Thank you!

Thanks, Giovanni!

**Pull request merged**
